// mobile/src/metronome/audioEmitter.ts
// The audible ClickEmitter — FLE-5 (Task 7).
//
// ---------------------------------------------------------------------------
// Why this file imports nothing from expo-audio
// ---------------------------------------------------------------------------
//
// `expo-audio` is not installed; FLE-5 requires that dependency be justified to
// Miagi first, and that decision is still open. So the player module is
// INJECTED rather than imported — exactly the discipline the engine already
// uses for `now` / `setTimer` / `clearTimer`. Consequences:
//
//   - This file typechecks and unit-tests today, with no package in the tree.
//   - The parts worth getting wrong-free — voice pooling, swallowing late
//     beats, accent selection, teardown — are written and covered NOW, instead
//     of being authored for the first time against a device after approval.
//   - If the answer is "ship it silent", nothing here is installed or shipped;
//     it is inert TypeScript.
//
// On approval, the ENTIRE remaining change is the call site:
//
//   // in MetronomeControl.tsx, after `npx expo install expo-audio`
//   import * as ExpoAudio from 'expo-audio';
//   import { createAudioClickEmitter, loadClickSources } from '../metronome/audioEmitter';
//   ...
//   useMetronome({
//     bpm,
//     beatsPerBar,
//     createEmitter: () => createAudioClickEmitter(ExpoAudio, loadClickSources()),
//   })
//
// API verified against the SDK 57 docs (https://docs.expo.dev/versions/v57.0.0/sdk/audio/):
// `createAudioPlayer(source, options)`, `player.play()`, `player.seekTo(seconds)`,
// `player.remove()`, `setAudioModeAsync(mode)`.
//
// The sounds themselves are already in the tree: assets/audio/tick.wav and
// accent.wav, generated by scripts/generate-click-assets.py.

import type { ClickEmitter, MetronomeBeat } from './types';

// ---------------------------------------------------------------------------
// The slice of expo-audio this adapter needs. Structural types, not imports —
// the real module satisfies these; the tests satisfy them with a fake.
// ---------------------------------------------------------------------------

export interface AudioPlayerLike {
  play(): void;
  /** expo-audio returns a promise here; the click deliberately does not await it. */
  seekTo(seconds: number): unknown;
  /** Frees the native player. */
  remove(): void;
}

export interface AudioModuleLike {
  createAudioPlayer(source: unknown): AudioPlayerLike;
  setAudioModeAsync?(mode: Record<string, unknown>): Promise<unknown>;
}

/** `require()`d asset handles for the two clicks. */
export interface ClickSources {
  tick: unknown;
  accent: unknown;
}

/**
 * The shipped click assets. Kept beside the adapter so the call site names one
 * thing, and so a re-tune (scripts/generate-click-assets.py) needs no code edit.
 *
 * A function rather than a module-level constant on purpose: `require` of an
 * asset is resolved by Metro at call time, so importing this module — which the
 * unit tests do — must not drag a .wav through whatever bundler is running.
 */
export function loadClickSources(): ClickSources {
  return {
    tick: require('../../assets/audio/tick.wav'),
    accent: require('../../assets/audio/accent.wav'),
  };
}

export interface AudioClickEmitterOptions {
  /**
   * Players allocated per sound, cycled round-robin.
   *
   * One player per sound is the obvious choice and the wrong one: `seekTo(0)`
   * is asynchronous, so re-triggering a single player means every click races
   * the rewind of the click before it. Two players means a beat always lands on
   * a player that has been idle for a full interval. More than two buys nothing
   * — a 35ms sound cannot still be playing two beats later, even at 300 BPM.
   */
  voicesPerSound?: number;
  /**
   * Called if the native layer throws while playing a beat. A failed click must
   * not take down the session, so the error is swallowed after this runs.
   */
  onError?: (error: unknown, beat: MetronomeBeat) => void;
}

export const DEFAULT_VOICES_PER_SOUND = 2;

/** Round-robin over a fixed set of players. */
function createVoicePool(
  audio: AudioModuleLike,
  source: unknown,
  size: number,
): { next(): AudioPlayerLike; removeAll(): void } {
  const players = Array.from({ length: Math.max(1, size) }, () => audio.createAudioPlayer(source));
  let cursor = 0;
  return {
    next() {
      const player = players[cursor];
      cursor = (cursor + 1) % players.length;
      return player;
    },
    removeAll() {
      for (const player of players) player.remove();
    },
  };
}

/**
 * Builds the audible emitter over an injected expo-audio module.
 *
 * Allocates every player up front: creating a native player costs file IO and
 * decode, which is not something to do on a beat deadline.
 */
export function createAudioClickEmitter(
  audio: AudioModuleLike,
  sources: ClickSources,
  options: AudioClickEmitterOptions = {},
): ClickEmitter {
  const { voicesPerSound = DEFAULT_VOICES_PER_SOUND, onError } = options;

  const tick = createVoicePool(audio, sources.tick, voicesPerSound);
  const accent = createVoicePool(audio, sources.accent, voicesPerSound);
  let disposed = false;

  return {
    emit(beat: MetronomeBeat) {
      if (disposed) return;
      // A beat that arrived closer to the NEXT beat than its own is worse than
      // no beat: it is heard as the pulse moving. Swallow it — the engine has
      // already advanced the grid, so the following click lands back in time.
      if (beat.late) return;

      const player = (beat.downbeat ? accent : tick).next();
      try {
        player.seekTo(0);
        player.play();
      } catch (error) {
        onError?.(error, beat);
      }
    },
    dispose() {
      if (disposed) return;
      disposed = true;
      tick.removeAll();
      accent.removeAll();
    },
  };
}

/**
 * Audio mode for a practice click. Call once before starting.
 *
 * `playsInSilentMode` is the load-bearing one: a phone propped on a music stand
 * is very often on the silent switch, and without this the metronome is
 * correct, running, and completely inaudible — which reads as a bug.
 *
 * `interruptionMode: 'mixWithOthers'` so the click coexists with a backing
 * track or the song the user is playing along to, rather than stopping it.
 */
export async function prepareClickAudioMode(audio: AudioModuleLike): Promise<void> {
  await audio.setAudioModeAsync?.({
    playsInSilentMode: true,
    shouldPlayInBackground: false,
    interruptionMode: 'mixWithOthers',
  });
}
