"""deploy-path probe: no schema change, exists only to be observed applying itself

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-24

FLE-68 — proof, not schema.

FLE-68 was filed believing the release path had no `alembic upgrade head` in it, on
the evidence of `server/Procfile` (which only starts uvicorn). That reading was wrong:
Railway reads `server/railway.toml` (the deployment manifest for SHA 8f5a91c records
`configFile: /server/railway.toml`), and that file has carried

    preDeployCommand = "alembic upgrade head"

since the very first server commit, fd6838e, 2026-07-16. Railway runs it in its own
container, to completion, before the new release takes traffic; a non-zero exit aborts
the deploy and the previous container keeps serving. The Procfile is dead config —
railway.toml's `startCommand` outranks it — and it is deleted in the same change that
adds this file, because being wrong in a way that reads as authoritative is the whole
reason this incident got written up.

So the mechanism was never missing. What was missing was a single observation of it
working. This revision is that observation: it changes NO schema, and its only effect
is to move `alembic_version.version_num` 0009 -> 0010. If prod reports 0010 after a
push that nobody ran alembic for by hand, the release path applies pending migrations
on its own. That is the entire point of the file.

Deliberately inert rather than a token DDL change (a table COMMENT was the obvious
alternative): alembic's autogenerate compares table comments, so a decorative comment
would surface as spurious drift in whatever the next autogenerated revision turns out
to be. A probe should not leave litter for the next person to reconcile.

Safe to keep, safe to squash away later. It asserts nothing about the schema.
"""

from alembic import op  # noqa: F401 — imported for symmetry with every other revision

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Intentionally empty. The observable side effect is alembic's own bookkeeping
    # UPDATE of alembic_version, which is what proves the pre-deploy container ran.
    pass


def downgrade() -> None:
    # Nothing to undo — upgrade() touched no schema.
    pass
