"""backfill_drills.py — bank drills from breakdowns that were already generated.

FLE-8 Task 3, final scope item. Migration 0006 created the bank; dedup-on-write and
per-drill history shipped with it. This script is the one-time (idempotent) load of
drills that are currently trapped inside `songs.breakdown` JSONB.

WHY A QUALITY GATE IS MANDATORY
-------------------------------
Every breakdown cached before the drill-prompt patch was generated by the prompt the
Task 1 eval graded as defective. Backfilling those rows banks exactly the drills the
eval flagged — a patched prompt only affects breakdowns generated AFTER it. So the
cutoff is not a convenience flag: running without one is how you get a bank of bad
drills, which is the specific failure FLE-8 is blocked on.

Hence one of these two is REQUIRED:
    --generated-after ISO8601   bank only breakdowns generated at/after this instant
    --include-pre-patch         bank everything, deliberately, eval be damned

USAGE (from the server/ directory):
    cd server
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5433/guitar_trainer \\
    python -m scripts.backfill_drills --generated-after 2026-09-16T17:43:41+03:00

Dry run is the DEFAULT — nothing is written without --apply. A dry run reports the
exact same per-drill decisions the write would make, so the plan is reviewable before
it is committed.

NO LLM IN THE WRITE PATH (FLE-8 constraint). Dedup is `app.ai.drill_dedupe.classify`,
which is pure rapidfuzz. The 70-84 uncertain band writes a `drill_dedupe_queue` row
for a human, exactly as the online write path does. This script never calls Sonnet.

IDEMPOTENT. Re-running is a no-op:
  - an already-banked drill scores 100 against itself -> REUSE, no row
  - an already-queued proposal is skipped by an explicit pending-queue check, so a
    second run does not pile up duplicate curator cards
"""
from __future__ import annotations

import argparse
import asyncio
import sys
import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.drill_dedupe import DedupeAction, build_candidates, classify
from app.db.session import AsyncSessionLocal
from app.models.db import Drill, DrillDedupeQueue, SkillNode, Song

# Content fields copied verbatim from the cached breakdown drill into the bank row.
# `mechanic_tier` is deliberately NOT here — it exists on the Pydantic wire shape but
# has no column on `drills`; copying it would raise rather than be silently dropped.
_CONTENT_FIELDS = (
    "song_specific",
    "what",
    "tab_snippet",
    "start_bpm",
    "target_bpm",
    "repetitions",
    "success_criterion",
)


class Counters:
    """Per-run tally. Printed as the report; also the assertion surface for tests."""

    def __init__(self) -> None:
        self.songs_scanned = 0
        self.songs_skipped_pre_patch = 0
        self.drills_seen = 0
        self.inserted = 0
        self.reused = 0
        self.queued = 0
        self.queue_already_pending = 0
        self.skipped_bad_skill_id = 0
        self.skipped_malformed = 0

    def as_dict(self) -> dict[str, int]:
        return dict(vars(self))


def _parse_cutoff(raw: str) -> datetime:
    """Parse the --generated-after cutoff, requiring an explicit timezone.

    `breakdown_generated_at` is timestamptz. Comparing it against a naive datetime
    raises in asyncpg rather than silently assuming UTC, so reject naive input here
    with a message that says what to add.
    """
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError as exc:
        raise SystemExit(f"--generated-after is not ISO 8601: {raw!r} ({exc})")
    if parsed.tzinfo is None:
        raise SystemExit(
            f"--generated-after needs an explicit timezone offset: {raw!r}\n"
            "e.g. 2026-09-16T17:43:41+03:00"
        )
    return parsed


def _extract_drills(breakdown: Any) -> list[dict[str, Any]]:
    """Pull the drills list out of a cached breakdown, tolerating pre-4.1 rows.

    Breakdowns cached before Phase 4.1 have no `drills` key at all, and the soft-fail
    path writes `drills: []`. Both are normal, not errors — return an empty list.
    """
    if not isinstance(breakdown, dict):
        return []
    drills = breakdown.get("drills")
    if not isinstance(drills, list):
        return []
    return [d for d in drills if isinstance(d, dict)]


async def _pending_queue_exists(
    db: AsyncSession,
    user_id: uuid.UUID,
    skill_node_id: uuid.UUID,
    proposed_name: str,
) -> bool:
    """Has this exact proposal already been queued and not yet resolved?

    Without this check a re-run re-queues every 70-84 drill, burying the curator in
    duplicate cards for decisions they have already been asked to make.
    """
    row = await db.execute(
        select(DrillDedupeQueue.id).where(
            DrillDedupeQueue.user_id == user_id,
            DrillDedupeQueue.skill_node_id == skill_node_id,
            DrillDedupeQueue.proposed_name == proposed_name,
            DrillDedupeQueue.status == "pending",
        ).limit(1)
    )
    return row.scalar_one_or_none() is not None


async def backfill(
    db: AsyncSession,
    *,
    cutoff: Optional[datetime],
    apply: bool,
    user_id: Optional[uuid.UUID] = None,
    verbose: bool = True,
) -> Counters:
    """Bank every drill in every eligible cached breakdown. Returns the tally.

    `user_id` narrows the load to one user — the POC has one, but the seams are
    stubbed for more, and a per-user run is the safe way to re-bank after a curator
    decision without re-walking the whole table.

    The caller owns the transaction: this function flushes so that in-run inserts are
    visible to later dedup passes, but never commits. `apply=False` means the caller
    rolls back — the decisions printed are still the real ones.
    """
    counters = Counters()

    query = select(Song).where(
        Song.user_id.isnot(None), Song.breakdown_generated_at.isnot(None)
    )
    if user_id is not None:
        query = query.where(Song.user_id == user_id)
    songs = (await db.execute(query.order_by(Song.id))).scalars().all()

    # Cache canonical drills per (user, skill) so dedup does not re-query per drill,
    # and so rows inserted EARLIER IN THIS RUN are scored against — a backfill that
    # only dedups against pre-existing rows would happily bank 60 copies of the same
    # idea in a single pass.
    bank: dict[tuple[uuid.UUID, uuid.UUID], list[Drill]] = {}

    async def candidates_for(user_id: uuid.UUID, skill_node_id: uuid.UUID) -> list[Drill]:
        key = (user_id, skill_node_id)
        if key not in bank:
            rows = (
                await db.execute(
                    select(Drill).where(
                        Drill.user_id == user_id,
                        Drill.skill_node_id == skill_node_id,
                        Drill.canonical_drill_id.is_(None),
                    )
                )
            ).scalars().all()
            bank[key] = list(rows)
        return bank[key]

    for song in songs:
        if cutoff is not None and song.breakdown_generated_at < cutoff:
            counters.songs_skipped_pre_patch += 1
            continue

        drills = _extract_drills(song.breakdown)
        if not drills:
            continue
        counters.songs_scanned += 1

        for index, raw in enumerate(drills):
            counters.drills_seen += 1
            name = raw.get("name")
            temp_id = raw.get("target_skill_temp_id")
            if not isinstance(name, str) or not name.strip() or not temp_id:
                counters.skipped_malformed += 1
                if verbose:
                    print(f"  SKIP song={song.id} drill={index} malformed (no name/skill id)")
                continue

            # `target_skill_temp_id` is not a temp id by the time it reaches the cache:
            # the breakdowns endpoint has Sonnet echo the real skill_node UUID back
            # (Landmine #2 defense). Re-verify it here anyway — the endpoint's check
            # ran against the skill list live at generation time, and a node deleted
            # since would leave a dangling id that the FK would reject mid-transaction.
            try:
                skill_node_id = uuid.UUID(str(temp_id))
            except ValueError:
                counters.skipped_bad_skill_id += 1
                if verbose:
                    print(f"  SKIP song={song.id} drill={index} skill id not a UUID: {temp_id!r}")
                continue

            owns_node = (
                await db.execute(
                    select(SkillNode.id).where(
                        SkillNode.id == skill_node_id,
                        SkillNode.user_id == song.user_id,
                    ).limit(1)
                )
            ).scalar_one_or_none()
            if owns_node is None:
                counters.skipped_bad_skill_id += 1
                if verbose:
                    print(
                        f"  SKIP song={song.id} drill={index} skill {skill_node_id} "
                        f"not owned by user {song.user_id}"
                    )
                continue

            missing = [f for f in _CONTENT_FIELDS if raw.get(f) is None]
            if missing:
                counters.skipped_malformed += 1
                if verbose:
                    print(f"  SKIP song={song.id} drill={index} missing {missing}")
                continue

            existing = await candidates_for(song.user_id, skill_node_id)
            decision = classify(name, build_candidates(existing, skill_node_id))

            if decision.action is DedupeAction.REUSE:
                counters.reused += 1
                if verbose:
                    print(
                        f"  REUSE song={song.id} drill={index} {name!r} "
                        f"-> {decision.matched_drill_id} (score {decision.score})"
                    )
                continue

            if decision.action is DedupeAction.QUEUE:
                if await _pending_queue_exists(db, song.user_id, skill_node_id, name):
                    counters.queue_already_pending += 1
                    if verbose:
                        print(f"  QUEUED-ALREADY song={song.id} drill={index} {name!r}")
                    continue
                db.add(
                    DrillDedupeQueue(
                        user_id=song.user_id,
                        proposed_name=name,
                        skill_node_id=skill_node_id,
                        candidate_drill_id=decision.matched_drill_id,
                        fuzzy_score=decision.score,
                        status="pending",
                        payload={
                            **raw,
                            "origin_song_id": song.id,
                            "origin_drill_index": index,
                        },
                    )
                )
                await db.flush()
                counters.queued += 1
                if verbose:
                    print(
                        f"  QUEUE song={song.id} drill={index} {name!r} "
                        f"~ {decision.matched_drill_id} (score {decision.score})"
                    )
                continue

            row = Drill(
                user_id=song.user_id,
                name=name,
                name_normalized=decision.name_normalized,
                skill_node_id=skill_node_id,
                canonical_drill_id=None,
                dedupe_score=decision.score,
                common_trap=raw.get("common_trap"),
                origin_song_id=song.id,
                origin_drill_index=index,
                **{f: raw[f] for f in _CONTENT_FIELDS},
            )
            db.add(row)
            await db.flush()
            existing.append(row)
            counters.inserted += 1
            if verbose:
                print(f"  INSERT song={song.id} drill={index} {name!r} -> {row.id}")

    return counters


def _report(counters: Counters, *, apply: bool) -> None:
    mode = "APPLIED" if apply else "DRY RUN (nothing written — pass --apply to commit)"
    print(f"\n=== drill backfill: {mode} ===")
    for key, value in counters.as_dict().items():
        print(f"  {key:<28} {value}")


async def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Backfill the drill bank from already-generated breakdowns.",
    )
    gate = parser.add_mutually_exclusive_group(required=True)
    gate.add_argument(
        "--generated-after",
        metavar="ISO8601",
        help=(
            "Only bank breakdowns generated at/after this instant, with an explicit "
            "timezone offset. Use the drill-prompt patch commit time."
        ),
    )
    gate.add_argument(
        "--include-pre-patch",
        action="store_true",
        help="Bank ALL cached breakdowns, including ones the Task 1 eval graded as defective.",
    )
    parser.add_argument(
        "--user-id",
        metavar="UUID",
        help="Limit the load to one user. Omit to walk every user with cached breakdowns.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Commit the writes. Without this the run is a dry run and rolls back.",
    )
    parser.add_argument("--quiet", action="store_true", help="Suppress per-drill lines.")
    args = parser.parse_args(argv)

    cutoff = _parse_cutoff(args.generated_after) if args.generated_after else None
    if cutoff is None:
        print(
            "WARNING: --include-pre-patch banks drills generated by the pre-patch "
            "prompt, which the Task 1 eval graded as defective.\n",
            file=sys.stderr,
        )

    async with AsyncSessionLocal() as db:
        counters = await backfill(
            db,
            cutoff=cutoff,
            apply=args.apply,
            user_id=uuid.UUID(args.user_id) if args.user_id else None,
            verbose=not args.quiet,
        )
        if args.apply:
            await db.commit()
        else:
            await db.rollback()

    _report(counters, apply=args.apply)
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(_main(sys.argv[1:])))
